### ISSUE TITLE
Error en mixins, no es posible usar la librería por sass

### ISSUE THREAD

**Issue by jahirvidrio** [escueladigital/EDgrid#104]
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected '.
   ╷
68 │             @debug ('
   │                      ^
   ╵
  node_modules\ed-grid\src\scss\ed-grid\helpers\_mixins.scss 68:22  @import
  node_modules\ed-grid\src\scss\ed-grid.scss 27:9                   @import
  node_modules\ed-grid\ed-grid.scss 1:9                             @import
```

**Comment by Jopzik** [comment]
Hola @jahirvidrio, ¿qué tal? Gracias por informarnos de este error, sería de gran ayuda que nos brindaras un poco más de información, como si estabas usando alguna función de EDgrid en Sass.

**Comment by jahirvidrio** [comment]
No estaba usando nada, hice la instalación con npm i ed-grid y al hacer la importación en mi archivo sass principal @import '~ed-grid/ed-grid'; nunca me dejó compilar y me daba ese mensaje de error.

**Comment by Jopzik** [comment]
¿Puedes mostrar el código de tu archivo Sass principal?

**Comment by jahirvidrio** [comment]
[Aquí](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=material&wt=none&l=sass&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=true&fl=1&fm=Hack&fs=12.5px&lh=133%25&si=false&es=2x&wm=false&code=%252F%252F%2520EDGrid%2520customization%250A%2524prototype%253A%2520false%253B%250A%250A%252F%252F%2520External%2520styles%250A%2540import%2520%27~ed-grid%252Fed-grid%27%253B%250A%2540import%2520url(%27https%253A%252F%252Ffonts.googleapis.com%252Fcss2%253Ffamily%253DBarlow%253Aital%252Cwght%25400%252C500%253B0%252C700%253B1%252C400%2526display%253Dswap%27)%253B%250A%250A%250A%253Aroot%2520%257B%250A%2520%2520--primary-color%253A%2520%252300addf%253B%250A%2520%2520--primary-color-alt%253A%2520%2523112EA4%253B%250A%250A%2520%2520--border-color%253A%2520%2523DDE5E8%253B%250A%250A%2520%2520--bg%253A%2520%2523f4f7f9%253B%250A%2520%2520--bg-light%253A%2520%2523ffffff%253B%250A%250A%2520%2520--text%253A%2520%2523455c6b%253B%250A%2520%2520--text-alt%253A%2520%252393acb0%253B%250A%2520%2520--text-disabled%253A%2520%2523cadbdf%253B%250A%2520%2520--text-content%253A%2520%25234c4c4c%253B%250A%250A%2520%2520--app-bar-box-shadow-color%253A%2520rgba(54%252C%252092%252C%2520108%252C%25200.5)%253B%250A%250A%2520%2520--app-nav-width%253A%2520130px%253B%250A%2520%2520--app-bar-height%253A%252060px%253B%250A%257D)

**Comment by Jopzik** [comment]
¿Y qué versión de EDgrid tienes instalada?

**Comment by jahirvidrio** [comment]
La última a día de hoy, acabo de realizar la instalación.

**Comment by Jopzik** [comment]
No he podido replicar el error, ¿podrías compartir la estructura Sass de tu proyecto para usarla en mi local?

**Comment by WilliBautista** [comment]
Hola! retomando el tema, también presento el mismo error al momento de importar ed-grid en mi sass tal cual lo hace @jahirvidrio, la versión que estoy utilizando también es la última a la fecha de hoy 3.0.1, estoy trabajando con la versión de sass 3.7.4.

Agreadezco la pronta respuesta!

Saludos!

**Comment by WilliBautista** [comment]
Hice una pequeña prueba quitando los espacios (enters) acomodando la sentencia del @debug en una sola linea y compilo sin error, al parecer el problema esta en los espacios o enters

Estructura que causa el error:
`// Modo debug para saber ver cómo se crearía el selector y el CSS resultante
          @if $debug {
            @debug ('
            @media screen and min-width(#{map-get($breakpoints, $size)}) {
              #{$selector} {
                #{$property} : #{$value}
              }
            }
            ');
          }`

Estructura que compila con exito.

`// Modo debug para saber ver cómo se crearía el selector y el CSS resultante
          @if $debug {
            @debug ('@media screen and min-width(#{map-get($breakpoints, $size)}) {#{$selector} {#{$property} : #{$value}}}');
          }`

**Comment by Jopzik** [comment]
Hola @WilliBautista, gracias por tu respuesta, ya mismo implemento eso que me comentas en el repositorio y ver si es la solución definitiva

**Comment by WilliBautista** [comment]
Dale, a mi me funciono!!

**Comment by Jopzik** [comment]
@WilliBautista ¿podrías probar en tu consola `npm install ed-grid@3.0.2-beta.1` y ver si todo marcha bien? Deshaciendo los cambios que hiciste, claro

**Comment by WilliBautista** [comment]
Claro, dame un momento te confirmo

**Comment by WilliBautista** [comment]
Solucionado! ahora ya compila sin problemas.

Muchas gracias por la pronta respuesta!

**Comment by Jopzik** [comment]
Al contrario, gracias a ti por tu colaboración. Ya se actualizó el repositorio y el proyecto en NPM con la versión 3.0.2
