### ISSUE TITLE
Será buena idea dejar los fonts en el core?

### ISSUE THREAD

**Issue by escueladigital** [escueladigital/EDgrid#16]
O los mandamos al template. Tengo esa duda.

**Comment by JonDotsoy** [comment]
Claro que si.

¿Que te parece usar `Icon-Font` basados en svg?

`https://www.npmjs.com/package/gulp-iconfont`

**Comment by Revod** [comment]
Me gusta la idea de @JonDotsoy y asi obtener también los svg, soy de los fieles creyentes de usar los iconos como svg y no como fonts, por la compatibilidad con los navegadores y la manipulación en css

**Comment by carloscuatin** [comment]
@escueladigital la verdad es que yo si prefiero que los icon fonts se vayan al template y que ed-grid sólo tenga su core en si. así es más limpio y mantenible

**Comment by JonDotsoy** [comment]
@carloscuatin con sass podemos requerir las utilidades necesarias. Por lo que no debiese ser problema el peso.

**Comment by escueladigital** [comment]
buen punto, si bien los fonts no son parte de ed grid como tal, si que nos ayudan mucho al momento de prototipar. Quizas se podria crear algo como edgrid-tools con botones, icons, forms, etc. ¿Podrá ser?

**Comment by carloscuatin** [comment]
@JonDotsoy claro, de hecho actualmente se hace de esa manera, el problema es que mandar iconfonts predeterminados. No me parece buena idea para ED-GRID ya que este framework es para full layout.

**Comment by carloscuatin** [comment]
@escueladogital exactamente, sería mejor un ed-tools y tomamos un poco la filosofía de purecss, si quieres más cosas pues agregas más modulos, pero si sólo necesitas el framework ED-GRID pues también debemos tener esa posibilidad

**Comment by JonDotsoy** [comment]
Me gusta mas la idea de levantar una continuidad de esta herramienta y levantar un framework mas potente. En verdad quedamos limitados si nos poneos a pensar en la filosofía como nace el proyecto.

**Comment by escueladigital** [comment]
pues bastaria un npm install --save edgrid-tools super facil, mejor que el core siga limpio, eso creo yo.

**Comment by carloscuatin** [comment]
@escueladigital claro y luego un @import en tu archivo scss

**Comment by JonDotsoy** [comment]
:+1:

**Comment by Revod** [comment]
Me parece una excelente idea :+1:

**Comment by carloscuatin** [comment]
@JonDotsoy aqui un ejemplo mira ah esto es lo que se quiere llegar https://github.com/basscss

**Comment by apaz074** [comment]
Buenas gente, veo que se están haciendo cambios en la estructura de ED-GRID y me gustaria compartir unas ideas, yo lo acomode de estas forma [https://github.com/apaz074/miversion](https://github.com/apaz074/miversion) y agrege unos mixins que cree. Digamen que les parece.
