### ISSUE TITLE
ED UI variantes dinamicas

### ISSUE THREAD

**Issue by iLenTheme** [escueladigital/EDgrid#21]
**1)** Me parece perfecto que todo este en ingles, o a su vez hagas una version en español y la misma en ingles para no dejar la lengua nativa del ed-grid, pero en si el ingles es todo. 
**2)** Los parametros de cabecera para cambiar el sufijos de la clase es realmente bueno asi podemos cosas con diferentes clases y perspectivas.
**3)** el ED UI aparte de hacer el theme standar de cada componente (el standar deber ser un tipo flat o meterial design moderno para ganarle a ese bootstrap) luego de eso debes tener una especie de clases con nombres {sufijo}-theme-{nombre_del_theme} ejemplo:
- accordion-theme-akatse
- accordion-theme-flatsolid
- accordion-theme-material1
- accordion-theme-material2
- (cada vez que salga nueva version de agrega nuevos themes para los componentes)

y para tener variante de color, el theme standar debe ser un plomo o azul (color psicologico de la modernidad) flat o paste, pero si el user quiere otro color en los filos o donde haya color en ese componente debe agregar las clase ejemplo:
- accordion-color-red
- accordion-color-turke
- accordion-color-gray
- accordion-color-silver
- accordion-color-orange
- accordion-color-{hexadecimal}

:)﻿

**Comment by mrcat29** [comment]
Interesante.
