### ISSUE TITLE
ed-item deberia de ser width:100%

### ISSUE THREAD

**Issue by dgaitan** [escueladigital/EDgrid#27]
En la documentacion de ed-grid se menciona la parte de que un ed-item por defecto tiene un width:100%, pero sin embargo no es asi, el width de un ed-item por defecto es automatico, cosa que puede ser un problema si se usa la version css. Para mi que deberia de quedar en width:100% ya que si por ejemplo en un ed-item solo va un texto o una imagen, este ed-item va a tener el ancho del hijo.

**Comment by escueladigital** [comment]
La documentación actual esta en proceso, lo que significa que va a ir cambiando hasta llegar a la versión final. En la versión anterior de ed-grid el hecho de que cada ed-item mida por defecto 100% recargaba el código css porque para darle otro valor habia que aumentar la especificidad del selector así:

```css
.ed-item.web-50,
.web-50 {
  width: 50%;
}
```
Ten en cuenta que las clases de ancho pueden aplicarse a cualquier elemento (no solo a un `ed-item`) , por eso se encadenan dos selectores.

Y esto con todos los breakpoints y todos los saltos de 5 en 5 y fracciones. Mucho css de más. Al quitar el width por defecto, el css resultante se reduce a solo

```css
.web-50 {
  width: 50%;
}
```

Y si se necesita un ed-item del 100% basta con

```html
<div class="ed-item l-100"> </div>
```
