### ISSUE TITLE
Remplazar gulp por npm scripts ?

### ISSUE THREAD

**Issue by carloscuatin** [escueladigital/EDgrid#29]

**Comment by francocorreasosa** [comment]
Creo que cubro parcialmente esta idea en #47

**Comment by idcmardelplata** [comment]
Creo que no hace falta reemplazar gulp, puesto que me parece que ofrece mucha mas funcionalidad que npm scripts, lo que si me parece una buena idea es simplemente correr gulp desde un script npm.

Podria ser algo asi:

```json
"start" : "./node_modules/.bin/gulp",
"watch" : "./node_modules/.bin/gulp sw"
````

**Comment by francocorreasosa** [comment]
Tecnicamente no es necesario el script `watch`, ya que el `start` ya incluye esa tarea.

**Comment by idcmardelplata** [comment]
jejeje tenes razón, sorry estoy re dormido ya a esta hora xd.
