### ISSUE TITLE
Revision de los mixin to() y from()

### ISSUE THREAD

**Issue by W-A-P** [escueladigital/EDgrid#33]
Tuve un incoveniente con esos mixin y es que se solapan, ya que "hasta" tal pixel cierto elemento adquiere su efecto pero en ese mismo pixel si se usa el mixin "desde" lo sobreescribe.
Es decir si uno establece hasta(m) y desde(m) en el pixel 640px hay una solapación, y por ejemplo me ha pasado que 2 elementos se quedaron en ese breakpoint "m" uno debajo de otro, y eso supongo yo que pasa porque el hasta(m) deberia tener efecto hasta los 639px y no como esta ahora.

Saludos !

**Comment by escueladigital** [comment]
No podemos restar unidades en el mixin porque se compila a `em` por lo que si usas `to(40em)` se compilaría como `39em` generando un problema mayor en el layout. Creo más bien que es un asunto de organización. El mixin `to()` está ahi para algunos casos raros que se presenten pero por lo general deberia usarse en lo posible solo `from()`
