### ISSUE TITLE
Comas al compilar fracciones en sass

### ISSUE THREAD

**Issue by rkmgralpaz** [escueladigital/EDgrid#37]
Descargué la versión 2.0 y no me funcionaban los tamaños en fracciones. Descubrí que se compilaron sin comas tal como muestra la imagen, tanto en m l  xl, solo a partir de las fracciones.

![captura](https://cloud.githubusercontent.com/assets/9677083/20228475/19302652-a830-11e6-81c7-418c215cf378.PNG)

**Comment by adri78** [comment]
1) Aca tienes la documentacion de ed-grid es para la primera beta.
https://www.dropbox.com/sh/y7tmzg7l0roxckq/AABuhKFmIXftx1EQrpEzcx0Pa?dl=0

2)Vuelve a bajar el sass, en particular el archivo _core.scss pues este debe tener un error.

**Comment by carloscuatin** [comment]
@rkmgralpaz que release tienes, podrias enviar una captura

**Comment by rkmgralpaz** [comment]
La versión 2.0 la ultima. Lo he arreglado agregando la coma en la función
de sass.

Otro problema que encontré es que al hacer por ejemplo:

<div class="ed-container full *s-main-center l-distribute*">, el tamaño mas
pequeño pisa al mas grande, y revisando el css (el que ya trae oficial y el
que me compila a mi usando sass) he notado que el sass compila salteado el
tamaño, lo adjunto en git
https://github.com/rkmgralpaz/prueba/edit/master/prueba.css

Las líneas que están fuera de secuencia son:

*11  16  21  26  31  36  45  50  55  60  65*

El tamaño s siempre está adelantado en uno, no sé si me explico!



2016-11-11 17:46 GMT-03:00 Carlos Cuatin <notifications@github.com>:

**Comment by escueladigital** [comment]
Corregido lo de las fracciones. Estoy viendo el otro caso ahora.

**Comment by rkmgralpaz** [comment]
Bueno, agradecería que me avisen cuando esté arreglado así continúo con el
tutorial, muchas gracias !!

2016-11-11 22:11 GMT-03:00 Escuela Digital <notifications@github.com>:
