### ISSUE TITLE
Implementacion de una wiki

### ISSUE THREAD

**Issue by idcmardelplata** [escueladigital/EDgrid#41]
Hola Álvaro, que te parecería armar un wiki con la documentación y los recursos disponibles sobre Ed-Grid?, así tanto el código como la documentación estarían en un mismo repo.

**Comment by francocorreasosa** [comment]
Yo sugeriría armar un repositorio con tipo `escueladigital/edgrid-docs` y armar la documentación en archivos markdown (`.md`) porque así se podria versionar y armar un sitio web que muestre la documentacion actualizada con cada commit.

**Comment by escueladigital** [comment]
Hay un grupo github.com/edgrid para todos los proyectos relacionados. Lo que no sé es si se pueden mover repos existentes ahi o deben forzosamente ser creados desde el inicio ahi.

**Comment by francocorreasosa** [comment]
Se puede hacer un fork y seguir el proyecto ahí.
De ultima un mirror.

**Comment by idcmardelplata** [comment]
Ha fantástico no sabía que existía ese repo
