### ISSUE TITLE
Error en el menu

### ISSUE THREAD

**Issue by foxfher** [escueladigital/EDgrid#42]
Error en el menú, al seleccionar una opción del menú que tiene un submenú lo muestra pero el alineado el la siguiente opción de menú. Es decir paso el ratón en en Acerca y muestra el submenú abajo de Productos, como muestra la imagen. Estoy siguiendo el ejemplo los paso del vídeo Cómo crear menús responsive con EDgrid 2
![image](https://cloud.githubusercontent.com/assets/22511692/20910297/4efeb3b2-bb26-11e6-84d7-60b2ec6d600f.png)

**Comment by escueladigital** [comment]
Corregido. Gracias por avisar
https://github.com/escueladigital/EDgrid/releases/tag/v2.0.1
