### ISSUE TITLE
Creacion de un generador de yeoman

### ISSUE THREAD

**Issue by idcmardelplata** [escueladigital/EDgrid#43]
Hola alvaro, he creado un generador para yeoman de ed-grid en su ultima versión. Ya es totalmente funcional aunque con un poco mas de tiempo pienso mejorarlo. Ya esta publicado en npm, así que puede utilizarse con el comando:

    npm install -g yo
    npm install -g generator-ed-grid

El enlace al repo (por si lo quieren revisar) es: https://github.com/idcmardelplata/generator-ed-grid

Espero les sea de su agrado. Un saludo :)

**Comment by escueladigital** [comment]
Que chevere 😄 Voy a probarlo.

**Comment by idcmardelplata** [comment]
Faltan agregarle las opciones, por ejemplo que genere diferentes salidas, tanto para sass como para css plano, también estoy trabajando en agregarle soporte para jade, handlebars y swig entre otros sistemas de templates, asi que ni bien lo tenga armado te aviso.

**Comment by idcmardelplata** [comment]
Ya soporta la selección de versiones, (css y sass), vi por ahí que un usuario te comentaba que hizo un fork de ed-grid y lo tradujo a stylus, no se si deseas también agregar esa opción al generador.  Por otro lado pensaba agregarle la opción de trabajar con distintos tipos de templates pero no se si sera mucho, estoy en duda todavía con eso. Si deseas mantenerlo simple lo dejamos asi y si deseas que tenga la opción para templates avísame y lo preparo. Un saludo.

**Comment by adri78** [comment]
yeoman  es EXCELENTE !!! gracias.

**Comment by idcmardelplata** [comment]
Por nada, no estoy seguro si agregarle para que haga el scafolding de jade también, puesto que no quiero mezclar edgrid con pug, si piensan que es necesario avisen y lo añado :)
