### ISSUE TITLE
[Sugerencia] Permitir cambiar prefijo "ed-"

### ISSUE THREAD

**Issue by francocorreasosa** [escueladigital/EDgrid#46]
Estaría genial poder cambiar el prefijo `ed` para las clases como `ed-container` y `ed-item` o directamente quitarlo.

Basicamente para generar una identidad del proyecto especifico en el código. 

De paso aprovecho para felicitar a todo el team de Escuela Digital por el excelente trabajo con el framework 👏👏

>**Nota:** Ya se que simplemente se puede ingresar a los archivos y reemplazar el `ed-`, pero hacerlo con una variable o algo parecido permitiría actualizar el framework sin tener que volver a repetir el proceso.

**Comment by escueladigital** [comment]
Antes de importar EDgrid a tu proyecto puedes cambiar esas clases reasignando valores a las variables. Así

```sass
$container: 'mi-container';
$item: 'mi-item';
@import 'path/ed-grid'
```
😄

**Comment by francocorreasosa** [comment]
¡Genial! Exactamente algo así buscaba. 🎉

Gracias.
