### ISSUE TITLE
remover los widgets de edgrid

### ISSUE THREAD

**Issue by idcmardelplata** [escueladigital/EDgrid#50]
hola, me parece que los componentes que no son relativos a la grilla deberían de ser extraídos de edgrid y puestos en otro repositorio, de esta manera se tendría una separación de responsabilidades mucho mas clara. Por ejemplo se podría hacer un repo llamado ed-widgets o ed-ui y poner allí todos los widgets (al mejor estilo bourbon y neat), de esta manera widgets como edmenu los botones etc... estarían aparte y el usuario podría opcionalmente usarlos o no. Ademas de que edgrid hace referencia a una grilla no a elementos de la ui. ¿que les parece la idea?

**Comment by escueladigital** [comment]
eventualmente todos los componentes de ui se moveran a otro proyecto llamado EDui, actualmente se han incluido en EDgrid solo el menu y los botones para facilitar el uso, pues muchos diseñadores no usarian EDgrid en sus proyectos sin faltan estos componentes. Pero una vez tengamos EDui, se saca todo eso de EDgrid.

**Comment by idcmardelplata** [comment]
ha copado, ¿te animas a hacer el repo así le voy copiando los componentes como el menú y los botones?
