### ISSUE TITLE
Sugerencia de dejar el valor del $gutter por defecto en 0em

### ISSUE THREAD

**Issue by W-A-P** [escueladigital/EDgrid#51]
Hola amigo Alvaro, me alegra que le haya gustado mi aporte al proyecto EDgrid.
Quería sugerir dejar el valor del $gutter por defecto en 0em, ya que en mi opinion adquiere una semantica mas clara ( lo cual sería una de las posibles soluciones al pequeño incoveniente que tuvo en uno de sus videos de la landing page ) . Es decir: 
* El no enviar un valor de gutter al mixin significa que no se quiere un gutter entre items
* El enviarle un valor al gutter es porque se requiere que tenga un gutter entre items.

Saludos !

**Comment by escueladigital** [comment]
Pensandolo bien es una buena idea. No solo por lo que comentas, sino que revisando el código he visto que para darle un gutter nulo hay que especificar una unidad. Es decir, pasarle 0 no funciona, debe ser 0px, 0em o 0rem lo cual es antinatural. Haré el cambio entonces.
