### ISSUE TITLE
Menu nav problema cuando esta en pequeño

### ISSUE THREAD

**Issue by berto1989** [escueladigital/EDgrid#53]
Buenas, estaba haciendo un menu de navegacion

> <nav class="ed-item s-80">
			 <ul class="ed-menu l-horizontal nav-bar">
			 	<li><a href="#">item 1</a></li>
			 	<li><a href="#">item 2</a>
					<ul>
			 	<li><a href="#">Subitem 1</a></li>
			 	<li><a href="#">Subitem 2</a></li>
			 	<li><a href="#">Subitem 3</a></li>
			 	<li><a href="#">Subitem 4</a></li>
			 	<li><a href="#">Subitem 5</a></li>
			 </ul>
			 	</li>
			 	<li><a href="#">item 3</a></li>
			 	<li><a href="#">item 4</a></li>
			 	<li><a href="#">item 5</a></li>
			 </ul>
		</nav>	

> 
Cuando al redimensionar el navegador para hacerlo como una tablet, veo que no despliega los submenus
![dsa](https://cloud.githubusercontent.com/assets/7673564/22286993/6736a58c-e2f1-11e6-8feb-bb499e301ddd.png)

es problema mio o de un fallo del grid?

**Comment by escueladigital** [comment]
Probablemente te falte añadir el codigo javascript

Álvaro Felipe Chávez

Escuela Digital Team Leader
http://escuela.digitalFacebook <http://escuela.digital/facebook> YouTube
<http://escuela.digital/youtube> Twitter <http://escuela.digital/twitter>
