### ISSUE TITLE
 error en EDgrid/components/_css-core.scss

### ISSUE THREAD

**Issue by jxamorro** [escueladigital/EDgrid#58]
Hola

creo que hay un error en el archivo  EDgrid/components/_css-core.scss

en la linea 42:

 &.radius { @include button(#DDD, 333, radius) 

falta una # en el color creo que debería ser:

 &.radius { @include button(#DDD, #333, radius)

Una vez corregido creo que hay que regenerar 
css/ed-grid.css  y css/ed-grid.min.css
porque tambien contienen el error

Saludos

**Comment by escueladigital** [comment]
Corregido, gracias por avisar.
