### ISSUE TITLE
Error con los botones en el core 

### ISSUE THREAD

**Issue by YeffKr** [escueladigital/EDgrid#69]
Buenas, ando probando EDgrid y al momento de compilar, me arroja un error en la línea 40 del _css-core.scss: dice no encontrar ningún mixin con el nombre "button".

**Comment by escueladigital** [comment]
el mixin button se ha renombrado a `edgridButton()` para evitar conflictos con EDui

**Comment by YeffKr** [comment]
Listo, el renombrado de los mixins tanto en _css-core y en _css-helpers, ha solucionado el error. 

¡Muchas gracias!
