### ISSUE TITLE
¿Cuál es la mejor forma de instalar EDgrid?

### ISSUE THREAD

**Issue by rjfortis7** [escueladigital/EDgrid#71]
Hola a todos, voy a empezar a usar EDgrid, queria consultarles cual sugieren es la mejor forma de instalarlo? ¿Como seria el entorno de desarrollo?

**Comment by alvarofelipe** [comment]
Hola @rjfortis7 Puedes usar EDgrid con Sass o CSS. Si lo usas con CSS basta incluir el archivo en tu proyecto y su usas Sass es mejor instalarlo con npm o yarn

```
npm install --save-dev ed-grid
```

Para más información ve a la documentacion http://ed-grid.com/documentacion.html

**Comment by rjfortis7** [comment]
Gracias @alvarofelipe estoy intentando trabajarlo con Sass pero tengo conocimientos basicos, asi que luego de intentar e intentar con `npm install --save-dev ed-grid` no logre entender como trabajarlo con gulp, asi que lo que hice fue:

- Instalar nodejs
- Instalar gulp
- Clonar el repositorio. git clone https://github.com/escueladigital/EDgrid.git
- Ejecutar en mi terminal `npm install` (para instalar todas las dependencias)
- Ejecutar en mi terminal `gulp`

Entonces me aparece lo siguiente:
[11:44:04] Failed to load external module @babel/register
[11:44:04] Requiring external module babel-register
[11:44:05] Using gulpfile ~/Documentos/EDgrid/gulpfile.babel.js
[11:44:05] Starting 'default'...
[11:44:07] Finished 'default' after 1.38 s

En la primer linea me aparece un error, aún asi me levanto el servidor. Creo que puedo trabajar sin problemas, verdad?

**Comment by carloscuatin** [comment]
@rjfortis7 aquí tienes un scaffolding https://github.com/edgrid/edgrid-template para que tengas un panorama mejor de como instalar y hacer uso de EDgrid 👍

**Comment by rjfortis7** [comment]
Muchas gracias @carloscuatin lo estoy revisando y me ha resultado genial +1

@alvarofelipe en esta URL:
http://ed-grid.com/botones.html

Este codigo scss no me funciona:
```
.selector1 { @include button(teal, white) }
.selector2 { @include button(tomato, white, round) }
.selector3 { @include button(#2e84e6, white, radius) }
```

Así si me funciono:
```
.selector1 { @include edgridButton(teal, white) }
.selector2 { @include edgridButton(tomato, white, round) }
.selector3 { @include edgridButton(#2e84e6, white, radius) }
```
