### ISSUE TITLE
Problemas al re-definir los breakpi 

### ISSUE THREAD

**Issue by DactJS** [escueladigital/EDgrid#76]
En la documentación nos indica que para re-definir los breakpoints tenemos que hacerlo de la siguientes manera, re-definiendo el map mostrado y luego importar ed-grid
![image](https://user-images.githubusercontent.com/48229829/64173898-4bf5f480-ce26-11e9-98db-91c2494bd8d8.png)

Pero al momentos de hacerlo, nos lanza un problema el compilar, y este entrando en el core del proyecto y me di cuenta que es porque en los breakpoints de la documentación hace falta el breakpoint 'l' para darle soporte a las versiones antiguas de ed-grid, la forma correcta para poder redefinir nuestros breakpoints sería:

![image](https://user-images.githubusercontent.com/48229829/64174145-adb65e80-ce26-11e9-925a-d39f3562af46.png)

**Comment by rubengvillar** [comment]
Hola no se como esta en la documentacion pero por regla básica y por estabilidad para redefinir una propiedad tenes que primero importar y luego redifinir. para sass es igual tambien el codigo se lee de arriba asi abajo por lo tanto si vos primero definis y luego importas la importacion estaria redifiniendo lo que vos definiste.

**Comment by DiegoCruzDev** [comment]
Si, comprendo, pero cuando tratas de modificar los breakpoints con nombres
diferentes, salta error, aún declarandolos antes de la importancion de
ed-grid
